### ISSUE TITLE
How to use the emit using vuejs / composition-api?

### ISSUE THREAD

**Issue by chrismichaelps** [u3u/vue-hooks#70]
Hi @u3u ,

You can provide an example of how to use a emit for this new vuejs API.?

I will be thankful. :)

**Comment by AlexVipond** [comment]
@ChrisMichaelPerezSantiago The example below uses `watch` from the composition API and the `useWindowSize` composition function from this repository to emit the window width whenever it changes.

The important line is 
```js
setup(props, { emit })
```

This works because [`setup` receives `context` as its second argument, and the `context` object contains the `emit` function](https://vue-composition-api-rfc.netlify.com/api.html#setup). 

```html
// App.vue
<template>
  <div id="app" style={{ width: widthPixel, height: heightPixel }}>
    dynamic window size: {width}, {height}
  </div>
</template>

<script>
import { watch } from '@vue/composition-api'

export default {
  setup(props, { emit }) {
    const { width, height, widthPixel, heightPixel } = useWindowSize()

    watch(() => {
      emit('window-width-changed', width)
    })
    
    return { width, height, widthPixel, heightPixel }
  }
}
</script>
```

**Comment by JetForMe** [comment]
What about for `<script setup>`?

**Comment by insideode** [comment]
Hi @JetForMe. Here is the script setup version:
<script setup>
import { defineEmits, watch } from 'vue';

const emit = defineEmits(['window-width-changed']);

watch(() => {
      emit('window-width-changed', width)
 })
</script>

**Comment by JetForMe** [comment]
Thanks for the answer; I did eventually figure that out.
